version: "3"
services:
  api:
    build: 
      context: .
      args:
        NODE_ENV: development
    ports:
      - "8000:8000"
    networks:
      - n1

    env_file:
      - ./.env
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run spin


networks:
  n1:
   
 
  